import Phaser from 'phaser';
import { addPixelBikeImage, makeWarmColorway, type BikeCategory } from './bike-pixel-sprite';
import type { BikeStats } from './meta-progress';
import { RIVERSIDE_ENDURANCE_RACE, applyRaceEntry, applyRaceReward, formatRaceTime, progressAt, simulateRace, type RaceResult } from './race-progress';

export type RaceCinematicHooks = { initialCoins?: number; stats?: BikeStats; dayNumber?: number; seed?: number; onSettled?: (value: { rank: number; reward: number; coins: number }) => void };
const META = RIVERSIDE_ENDURANCE_RACE; const INK = 0x3b2531; const CREAM = 0xfff1c6; const RED = 0xc95746; const GREEN = 0x5e9a67; const GOLD = 0xf4b84a; const WOOD = 0xa9683f; const DARK = 0x573044;
type Visual = { container: Phaser.GameObjects.Container; wheels: Phaser.GameObjects.Arc[]; racer: RaceResult['racers'][number]; progress: number; last: number; pedal: Phaser.GameObjects.Rectangle };
class RaceE extends Phaser.Scene {
  private coins = 0; private result?: RaceResult; private visuals: Visual[] = []; private playMs = 0; private speed = 1; private racing = false;
  constructor(private hooks: RaceCinematicHooks) { super('release-race-e'); }
  create() { this.coins = this.hooks.initialCoins ?? 2480; this.entry(); }
  private txt(x:number,y:number,text:string,size=12,color='#fff1c6'){return this.add.text(x,y,text,{fontFamily:'Arial, sans-serif',fontSize:`${size}px`,color,fontStyle:'bold'});}
  private bg(){this.add.rectangle(195,405,390,810,WOOD); for(let y=0;y<810;y+=26)this.add.rectangle(195,y,390,2,0x8a5231,.45);}
  private entry(){this.bg();this.txt(195,32,'RIVERSIDE 3K · CINEMATIC RACE E',15).setOrigin(.5);this.txt(195,60,'DAY '+(this.hooks.dayNumber??5)+' · 캐릭터/바퀴/페달링 · x4 지원',10).setOrigin(.5);addPixelBikeImage(this,195,250,3,{category:'road',colorway:makeWarmColorway(RED)});this.txt(195,360,'스포츠 중계형 자동 레이스',20).setOrigin(.5);this.txt(195,400,'3,000m · 참가비 500 · 결과 선확정 후 연출 재생',11).setOrigin(.5);const b=this.add.rectangle(195,500,300,52,GREEN).setStrokeStyle(4,INK).setInteractive({useHandCursor:true});this.txt(195,500,'레이스 시작',16).setOrigin(.5);b.on('pointerdown',()=>{const e=applyRaceEntry(this.coins,META);if(!e.ok)return;this.coins=e.coins;this.result=simulateRace({seed:this.hooks.seed??20260903,playerStats:this.hooks.stats??{성능:3,스타일:2,희귀도:2},meta:META});this.start();});}
  private start(){this.children.removeAll(true);this.visuals=[];this.add.rectangle(195,210,390,420,0x86c9c8);this.add.rectangle(195,350,390,120,0xb66f45);for(let x=0;x<420;x+=52)this.add.rectangle(x,385,25,4,CREAM,.7);this.result!.racers.forEach((r,i)=>{const c=this.add.container(-80,325+(i%4)*18);const rear=this.add.circle(-36,0,14,0x000000,0).setStrokeStyle(2,0xd9c197);const front=this.add.circle(36,0,14,0x000000,0).setStrokeStyle(2,0xd9c197);c.add([rear,front]);const bike=addPixelBikeImage(this,0,0,2,{category:r.category as BikeCategory,colorway:makeWarmColorway(r.frameColor)});c.add(bike);const body=this.add.rectangle(-4,-45,14,25,r.isPlayer?RED:r.frameColor).setAngle(22).setStrokeStyle(2,INK);const head=this.add.circle(4,-64,8,0xeeb07c).setStrokeStyle(2,INK);const pedal=this.add.rectangle(0,7,24,4,0xa39985);c.add([body,head,pedal]);this.visuals.push({container:c,wheels:[rear,front],racer:r,progress:0,last:0,pedal});});this.add.rectangle(195,610,390,400,WOOD);this.txt(15,15,'LIVE · '+META.name,13);this.txt(15,42,'속도감: 국면별 배경 이동 + 스포크/크랭크 회전',9);const sb=this.add.rectangle(300,70,150,36,GREEN).setStrokeStyle(3,INK).setInteractive({useHandCursor:true});const st=this.txt(300,70,'중계 속도 x1',11).setOrigin(.5);sb.on('pointerdown',()=>{this.speed=this.speed===1?2:this.speed===2?4:1;st.setText(`중계 속도 x${this.speed}`);sb.setFillStyle(this.speed===4?RED:this.speed===2?GOLD:GREEN);if(this.speed===4)this.cameras.main.shake(120,.004);});this.racing=true;}
  update(_:number,delta:number){if(!this.racing||!this.result)return;this.playMs+=delta*this.speed;const tick=this.playMs/this.result.tickMs;const ordered=this.visuals.map(v=>{v.progress=progressAt(v.racer.timeline,tick);return v;}).sort((a,b)=>b.progress-a.progress);const player=this.visuals.find(v=>v.racer.isPlayer)!;ordered.forEach((v,i)=>{const moved=Math.max(0,v.progress-v.last);v.last=v.progress;v.container.x=Phaser.Math.Linear(v.container.x,145+(v.progress-player.progress)*1000,.15);v.container.y=340+(i%4)*14+Math.sin(this.playMs*.012+i)*2;const spin=moved*2600/18;v.wheels.forEach(w=>w.rotation+=spin);v.pedal.rotation+=spin*1.8;});if(player.progress>.82)this.cameras.main.shake(30,this.speed===4?.002:.0008);if(player.progress>=1){this.racing=false;this.time.delayedCall(500,()=>this.resultScreen());}}
  private resultScreen(){this.children.removeAll(true);this.bg();const p=this.result!.racers.find(r=>r.isPlayer)!;this.txt(195,100,'PHOTO FINISH',28).setOrigin(.5);this.txt(195,155,`${p.rank}위 · ${formatRaceTime(p.finishTimeMs)}`,22).setOrigin(.5);const reward=applyRaceReward(this.coins,p.rank,META);this.txt(195,250,`보상 +${reward.reward} 코인`,18).setOrigin(.5);const b=this.add.rectangle(195,340,280,50,GREEN).setStrokeStyle(4,INK).setInteractive({useHandCursor:true});this.txt(195,340,'보상 받고 Garage로',14).setOrigin(.5);b.on('pointerdown',()=>{this.coins=reward.coins;this.hooks.onSettled?.({rank:p.rank,reward:reward.reward,coins:reward.coins});});}
}
export function startRaceCinematicBroadcast(parent:string,hooks:RaceCinematicHooks={}){return new Phaser.Game({type:Phaser.AUTO,width:390,height:810,parent,pixelArt:true,roundPixels:true,scene:new RaceE(hooks),scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});}
